spring.application.name=dan-ia

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3:14b
spring.ai.ollama.init.pull-model-strategy=never
spring.ai.ollama.init.timeout=5m
spring.ai.ollama.init.max-retries=0
spring.ai.ollama.init.chat.include=true
spring.ai.ollama.init.chat.additional-models=[]